"""
DeepShield — CLIP AI-Image Detection Module (v10 — Tighter Calibration)
========================================================================
Key calibration changes from v9:
  - Balanced prompts: 10 real vs 12 AI
  - Calibration clamp threshold tightened: any single real-prompt > 0.06 (was 0.10)
    → A 10% threshold fired even on synthetic images; 6% is tight enough to catch
      genuinely-strong real signals while ignoring low-weight noise.
  - Cap lowered from 0.72 → 0.62 (safely below THRESHOLD_AI=0.65)
    → Ensures a clamped image can NEVER be classified as AI Generated by the ensemble.
"""

import io
import logging
import torch
import numpy as np
from PIL import Image
from transformers import CLIPProcessor, CLIPModel

logger = logging.getLogger(__name__)

CLIP_MODEL_ID = "openai/clip-vit-large-patch14"
_model     = None
_processor = None

# ── Real photo anchors (10 — balanced with AI prompts) ────────────────────
# Covers the common cases that were false-positiving: indoor portraits, phones,
# red/plain backgrounds, studio setups, etc.
REAL_PROMPTS = [
    "a real photograph taken by a camera",
    "authentic photo with natural lighting and camera sensor noise",
    "real life candid photograph with natural depth of field",
    "photo taken with a smartphone camera",
    "photojournalism style real documentary photograph",
    "a real person photographed indoors with flash",
    "a genuine portrait photograph of a real human being",
    "a compressed JPEG photo shared on WhatsApp or social media",
    "a real photo of a person in front of a plain background",
    "a natural photograph captured at an event or gathering",
]

# ── AI generator anchors (12 — unchanged) ─────────────────────────────────
AI_PROMPTS = [
    "an image generated by artificial intelligence",
    "AI generated digital art created by a neural network",
    "a synthetic image created by Stable Diffusion or Midjourney",
    "image created by Google Gemini AI image generation",
    "image generated by DALL-E 3 by OpenAI",
    "image created by Adobe Firefly generative AI",
    "AI generated photorealistic image by Imagen or Parti",
    "deepfake or AI synthesized photograph of a person",
    "GAN generated face or image by StyleGAN or similar",
    "image created by Leonardo AI or Bing Image Creator",
    "synthetic media created by diffusion model AI",
    "computer generated photorealistic portrait by AI",
]


def _get_model():
    global _model, _processor
    if _model is None:
        logger.info(f"Loading CLIP model ({CLIP_MODEL_ID}) — first run ~1.7 GB ...")
        device = "cuda" if torch.cuda.is_available() else "cpu"
        _processor = CLIPProcessor.from_pretrained(CLIP_MODEL_ID)
        _model     = CLIPModel.from_pretrained(CLIP_MODEL_ID)
        _model.to(device)
        _model.eval()
        logger.info("CLIP model loaded.")
    return _model, _processor


def _device():
    return "cuda" if torch.cuda.is_available() else "cpu"


def run(image_bytes: bytes) -> dict:
    try:
        img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
        model, processor = _get_model()
        device = _device()

        all_prompts = REAL_PROMPTS + AI_PROMPTS
        inputs = processor(text=all_prompts, images=img, return_tensors="pt", padding=True).to(device)

        with torch.no_grad():
            outputs = model(**inputs)
            logits  = outputs.logits_per_image   # [1, N]
            probs   = logits.softmax(dim=-1)[0].cpu().numpy()

        n_real      = len(REAL_PROMPTS)
        real_probs  = probs[:n_real]
        ai_probs    = probs[n_real:]

        real_prob = float(np.sum(real_probs))
        ai_prob   = float(np.sum(ai_probs))

        total = real_prob + ai_prob
        if total > 0:
            real_prob /= total
            ai_prob   /= total

        # Per-prompt breakdown for UI / debugging
        real_scores = {p: float(real_probs[i])  for i, p in enumerate(REAL_PROMPTS)}
        ai_scores   = {p: float(ai_probs[i])    for i, p in enumerate(AI_PROMPTS)}

        # Best-matching prompts from each side
        top_ai_prompt   = max(ai_scores,   key=ai_scores.get)
        top_real_prompt = max(real_scores, key=real_scores.get)
        top_ai_score    = ai_scores[top_ai_prompt]
        top_real_score  = real_scores[top_real_prompt]

        logger.info(
            f"CLIP: ai={ai_prob:.3f} real={real_prob:.3f} "
            f"| top-AI='{top_ai_prompt[:40]}' ({top_ai_score:.3f})"
            f"| top-real='{top_real_prompt[:40]}' ({top_real_score:.3f})"
        )

        # ── Safety clamp: if a real prompt has strong individual support, cap ai ─
        # Prevents misclassifying clear real-person photos where CLIP votes split.
        # Threshold 0.06: tight enough to fire only on genuinely real signals;
        # 0.10 was too loose and allowed real faces to stay just below the cap.
        # Cap 0.62: safely below THRESHOLD_AI (0.65) so clamped images are never
        # classified as AI Generated by the ensemble.
        max_real_single = float(np.max(real_probs))
        if max_real_single > 0.06 and ai_prob < 0.85:
            # At least one real prompt is well-supported — be conservative
            ai_prob   = min(ai_prob, 0.62)
            real_prob = 1.0 - ai_prob

        # ── NO unconditional 1.12x boost (removed — was the primary FP source) ──

        return {
            "ai_prob":            round(ai_prob,        4),
            "real_prob":          round(real_prob,       4),
            "real_prompt_scores": real_scores,
            "ai_prompt_scores":   ai_scores,
            "top_ai_signal":      top_ai_prompt,
            "top_real_signal":    top_real_prompt,
            "available":          True,
        }

    except Exception as exc:
        logger.error(f"CLIP model error: {exc}")
        return {
            "ai_prob": 0.0, "real_prob": 1.0,
            "real_prompt_scores": {}, "ai_prompt_scores": {},
            "top_ai_signal": "", "top_real_signal": "",
            "available": False, "error": str(exc),
        }
